parameters:
  - name: serviceConnectionName
    displayName: Azure Resource Manager Service Connection
    type: string
  - name: manualLogin
    displayName: Manual login required?
    type: boolean
    default: false
  - name: imageType
    displayName: OS of the created image
    type: string
    values:
      - Ubuntu2204
      - Ubuntu2004
      - Ubuntu1804
      - Windows2022
      - Windows2019
  - name: imageCreationAgent
    displayName: Name of agent that runs image creation. 'MS' for Microsoft-hosted.
    type: string
  - name: azureLocation
    displayName: Azure Location where resources will be created
    type: string
  - name: agentResourceGroup
    displayName: Resource group where agent(s) are deployed to
    type: string
  - name: networkResourceGroupName
    displayName: Resource group of agent network
    type: string
  - name: networkVnetName
    displayName: Vnet of agent network
    type: string
  - name: networkSubnetName
    displayName: Subnet of agent network
    type: string
  - name: keyVaultName
    displayName: Keyvault to store agent login credentials
    type: string

variables:
- template: agent-pool-variables.yml
  parameters:
    acgName: "acgdevopsagents"
    imageType: ${{ parameters.imageType }}

jobs:
  - template: jobs/agent-pool-check-template.yml
    parameters:
      serviceConnectionName: "${{ parameters.serviceConnectionName }}"
      agentPoolName: "${{ variables.AgentPoolName }}"
      agentResourceGroup: "${{ parameters.agentResourceGroup }}"
  - template: jobs/agent-image-creation-template.yml
    parameters:
      imageCreationAgent: ${{ parameters.imageCreationAgent }}
      serviceConnectionName: "${{ parameters.serviceConnectionName }}"
      manualLogin: "${{ parameters.manualLogin }}"
      imageType: "${{ variables.ImageType }}"
      azureLocation: "${{ parameters.azureLocation }}"
  - template: jobs/agent-image-version-template.yml
    parameters:
      serviceConnectionName: "${{ parameters.serviceConnectionName }}"
      resourceGroupName: "${{ parameters.agentResourceGroup }}"
      galleryName: "${{ variables.AcgName }}"
      imageName: "${{ variables.ImageName }}"
  - template: jobs/agent-infrastructure-creation-template.yml
    parameters:
      dependsOn:
        - jobCheckAgent
        - jobCreatePackerImg
        - jobSetPackerImgVersion
      serviceConnectionName: "${{ parameters.serviceConnectionName }}"
      imageType: "${{ variables.ImageType }}"
      azureLocation: "${{ parameters.azureLocation }}"
      agentResourceGroup: "${{ parameters.agentResourceGroup }}"
      networkResourceGroupName: "${{ parameters.networkResourceGroupName }}"
      networkVnetName: "${{ parameters.networkVnetName }}"
      networkSubnetName: "${{ parameters.networkSubnetName }}"
      keyVaultName: "${{ parameters.keyVaultName }}"
      acgName: "${{ variables.AcgName }}"
  - template: jobs/agent-pool-creation-template.yml
    parameters:
      serviceConnectionName: "${{ parameters.serviceConnectionName }}"
      agentPoolName: "${{ variables.AgentPoolName }}"
      agentResourceGroup: "${{ parameters.agentResourceGroup }}"
  - template: jobs/agent-image-cleanup-template.yml
    parameters:
      serviceConnectionName: "${{ parameters.serviceConnectionName }}"
      imageType: "${{ variables.ImageType }}"