parameters:
  - name: serviceConnectionName
    displayName: Azure Resource Manager Service Connection
    type: string
  - name: imageName
    displayName: Name of the created Ubuntu image
    type: string
  - name: azureLocation
    displayName: Azure Location where resources will be created
    type: string
  - name: agentResourceGroup
    displayName: Resource group where agent(s) are deployed to
    type: string
  - name: networkResourceGroupName
    displayName: Resource group of agent network
    type: string
  - name: networkVnetName
    displayName: Vnet of agent network
    type: string
  - name: networkSubnetName
    displayName: Subnet of agent network
    type: string
  - name: keyVaultName
    displayName: Keyvault to store agent login credentials
    type: string

variables:
  - template: agent-pool-variables.yml
    parameters:
      imageType: ${{ parameters.imageName }}
jobs:
  - template: jobs/agent-pool-check-template.yml
    parameters:
      serviceConnectionName: "${{ parameters.serviceConnectionName }}"
      agentPoolName: "${{ variables.AgentPoolName }}"
      agentResourceGroup: "${{ parameters.agentResourceGroup }}"
  - template: jobs/agent-infrastructure-creation-template.yml
    parameters:
      serviceConnectionName: "${{ parameters.serviceConnectionName }}"
      imageType: "${{ variables.ImageType }}"
      azureLocation: "${{ parameters.azureLocation }}"
      agentResourceGroup: "${{ parameters.agentResourceGroup }}"
      networkResourceGroupName: "${{ parameters.networkResourceGroupName }}"
      networkVnetName: "${{ parameters.networkVnetName }}"
      networkSubnetName: "${{ parameters.networkSubnetName }}"
      keyVaultName: "${{ parameters.keyVaultName }}"
  - template: jobs/agent-pool-creation-template.yml
    parameters:
      serviceConnectionName: "${{ parameters.serviceConnectionName }}"
      agentPoolName: "${{ variables.AgentPoolName }}"
      agentResourceGroup: "${{ parameters.agentResourceGroup }}"