#TODO: Set parameters here
parameters:
  # general parameters:
  - name: serviceConnectionName
    displayName: Azure Resource Manager Service Connection
    type: string
    default: XXXXXXXXXXXXXXXXXXXXXX
  - name: imageName
    displayName: Name of the created Ubuntu image
    type: string
    default: UbuntuXS
  # parameters to create infrastructure:
  - name: azureLocation
    displayName: Azure Location where resources will be created
    type: string
    default: XXXXXXXXXXXXXXXXXXXXXX
  - name: agentResourceGroup
    displayName: Resource group where agent(s) are deployed to
    type: string
    default: XXXXXXXXXXXXXXXXXXXXXX
  - name: networkResourceGroupName
    displayName: Resource group of agent network
    type: string
    default: XXXXXXXXXXXXXXXXXXXXXX
  - name: networkVnetName
    displayName: Vnet of agent network
    type: string
    default: XXXXXXXXXXXXXXXXXXXXXX
  - name: networkSubnetName
    displayName: Subnet of agent network
    type: string
    default: XXXXXXXXXXXXXXXXXXXXXX
  - name: keyVaultName
    displayName: Keyvault to store agent login credentials
    type: string
    default: XXXXXXXXXXXXXXXXXXXXXX

trigger: none

extends:
  template: templates/agent-pool-prebuilt-template.yml
  parameters:
    serviceConnectionName: "${{ parameters.serviceConnectionName }}"
    imageName: "${{ parameters.imageName }}"
    azureLocation: "${{ parameters.azureLocation }}"
    agentResourceGroup: "${{ parameters.agentResourceGroup }}"
    networkResourceGroupName: "${{ parameters.networkResourceGroupName }}"
    networkVnetName: "${{ parameters.networkVnetName }}"
    networkSubnetName: "${{ parameters.networkSubnetName }}"
    keyVaultName: "${{ parameters.keyVaultName }}"